-- Fix id_documento identity constraint: sequence outgrew the check limit
-- The column is GENERATED BY DEFAULT AS IDENTITY, but existing sequence
-- values exceeded the CHECK (id_documento <= 9), breaking INSERTs.

ALTER TABLE public.clientes DROP CONSTRAINT IF EXISTS clientes_id_documento_check;

-- Restart identity at the next available value if table has rows
DO $$
DECLARE
    v_max BIGINT;
BEGIN
    SELECT COALESCE(MAX(id_documento), 0) + 1 INTO v_max FROM public.clientes;
    EXECUTE format('ALTER TABLE public.clientes ALTER COLUMN id_documento RESTART WITH %s', v_max);
END $$;
